export const BRANDS = [
  'Rabbani (KAS, KAA, KAF)',
  'Busana Ikhwan (Kemko, Hiro)',
  'Busana Akhwat (Dresslim, Dluha)',
  'Sarung (Palestine Style)',
  'Perlengkapan (Kaxit, dll)',
  'Busanan Anak (Bani)',
  'Motifashion, Megura',
  'Offline Store',
  'Special Events',
];

export const JOB_TYPES = [
  { id: 'voucher', label: 'Voucher' },
  { id: 'poster_a3_a4', label: 'Poster A3/A4' },
  { id: 'flyer_a5', label: 'Flyer A5' },
  { id: 'flyer_a6', label: 'Flyer A6' },
  { id: 'blash_3_4', label: 'Blash 3;4' },
  { id: 'blash_15_9', label: 'Blash 15;9' },
  { id: 'katalog', label: 'Katalog' },
  { id: 'x_banner', label: 'X Banner' },
  { id: 'video_reels_organik', label: 'Video Reels Organik' },
  { id: 'video_youtube', label: 'Video Youtube' },
  { id: 'video_ads', label: 'Video Ads' },
  { id: 'carousel_post_ads', label: 'Carousel post Ads' },
  { id: 'carousel_post_organik', label: 'Carousel post organik' },
  { id: 'square_post_ads', label: 'Square post ads' },
  { id: 'square_post_organik', label: 'Square post organik' },
  { id: 'portrait_story_sosmed', label: 'Portrait story sosmed' },
  { id: 'paket_cta_video_4_ukuran', label: 'Paket CTA video ( 4 ukuran )' },
  { id: 'audioline', label: 'Audioline' },
  { id: 'ooh_spanduk_baligho', label: 'OOH ( spanduk, baligho )' },
  { id: 'window_display_sticker', label: 'Window display sticker' },
  { id: 'pintu_store', label: 'Pintu Store' },
  { id: 'pov', label: 'Pov' },
  { id: 'wobbler', label: 'Wobbler' },
  { id: 'sign_system_store', label: 'Sign system store' },
  { id: 'backdrop', label: 'Backdrop' },
  { id: 'banner_shopee', label: 'Banner shopee' },
  { id: 'cover_video', label: 'Cover video' },
  { id: 'overlay', label: 'Overlay' },
  { id: 'motion_grafis', label: 'Motion Grafis' }
];
